version: "3"
services:
  app:
    build: ./app
    volumes:
      - "./app:/app"

  proxy:
    image: ghcr.io/ochanoco/torima:develop
    volumes:
      - "./proxy/data:/workspace/data"
      - "./proxy/config.yaml:/workspace/config.yaml"
    environment:
      - TORIMA_DB_TYPE=sqlite3
      - TORIMA_DB_CONFIG=file:./data/db.sqlite3?_fk=1
    env_file:
      - ./proxy/secret.env
    ports:
      - "8080:8080"

